version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app-timesheet:
    depends_on:
      - mysqldb
    image: amirakhalfi/tp-foyer:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",  
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect", 
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

  sonarqube:
    image: sonarqube:8.9.7-community
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extensions:/opt/SonarQube/extensions'
      - 'SonarQube_logs:/opt/SonarQube/logs'

volumes:
  db:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
