version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      - backend

  tp-foyer:
    image: tp-foyer-backend:latest
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8089
    ports:
      - "8088:8089"
    networks:
      - backend

  app-timesheet:
    image: app-timesheet:latest
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8089
    ports:
      - "8088:8089"
    networks:
      - backend

volumes:
  mysqldb_data:

networks:
  backend:
